site_name: Saboteur Team Wiki
theme: readthedocs
nav:
  - Home: index.md
  - Game:
    - Index: 'game/index.md'
    - Client:
      - Index: 'game/client/index.md'
      - Random Offsets: 'game/client/random_offsets.md'
    - Crc: 'game/crc.md'
    - Filesystem: 'game/filesystem.md'
    - File formats:
      - Index: 'game/formats/index.md'
      - GameText: 'game/formats/gametext.md'
      - LooseFiles: 'game/formats/loosefiles.md'
      - LuaScripts: 'game/formats/luap.md'
      - Megapack/Kilopack: 'game/formats/megapack.md'
      - France FSM: 'game/formats/france_fsm.md'
      - France FST: 'game/formats/france_fst.md'
      - Shaders: 'game/formats/shaders.md'
      - France HEI: 'game/formats/france_hei.md'
      - France Ambush: 'game/formats/france_ambush.md'
      - France Cinsplines: 'game/formats/france_cinsplines.md'
      - France Defen: 'game/formats/france_defen.md'
      - France Freeplay: 'game/formats/france_freeplay.md'
      - France GpsGraph: 'game/formats/france_gpsgraph.md'
      - France HQPoints: 'game/formats/france_hqpoints.md'
      - France Paths: 'game/formats/france_paths.md'
      - France Railway: 'game/formats/france_railway.md'
      - France RNDNodes: 'game/formats/france_rndnodes.md'
      - France Spore: 'game/formats/france_spore.md'
      - France Trigs: 'game/formats/france_trigs.md'
    - Lua: 'game/lua/index.md'
    - Versions: 'game/versions.md'
  - Tools:
    - Index: 'tools/index.md'
    - SabTool: 'tools/sabtool.md'
